version: "3.3"
services:
  nodejs:
    container_name: nodejs
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./nodejs:/usr/src/app

  postgres:
    image: postgis/postgis
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=cmu_commu
    ports:
      - "5433:5432"
    volumes:
      - ./postgres/cmu_commu.sql:/docker-entrypoint-initdb.d/cmu_commu.sql

  geoserver:
    container_name: geoserver
    depends_on:
      - postgres
    image: tomcat:8.5.79-jre8
    volumes:
      - ./tomcat_webapps/:/usr/local/tomcat/webapps/
      - ./tomcat_webapps/fonts/truetype/:/usr/share/fonts/truetype/
    ports:
      - '8080:8080'
