version: "3.3"
services:
  nginx:
    image: nginx
    # build: ./nginx
    depends_on:
      - nodejs
      - tomcat
    ports:
      - "80:80"
    volumes:
      # - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  nodejs:
    image: "node"
    working_dir: /home/node/app
    restart: always
    depends_on:
      - postgres
      - tomcat
    environment:
      - NODE_ENV=production
    volumes:
      - ./nodejs:/home/node/app
    ports:
      - '3000:3000'
    command: bash -c "npm i && npm i -g nodemon && nodemon server.js"

  postgres:
    image: postgis/postgis
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=cmu_commu
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/cmu_commu.sql:/docker-entrypoint-initdb.d/cmu_commu.sql

  tomcat:
    depends_on:
      - postgres
    image: tomcat:8-jre11
    volumes:
      - ./tomcat/:/usr/local/tomcat/webapps/
      - ./tomcat/fonts/truetype/:/usr/share/fonts/truetype/
    ports:
      - '8080:8080'
