version: "3.3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app/

  postgres:
    image: postgis/postgis
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=cmu_commu
    ports:
      - "5433:5432"
    volumes:
      - ./cmu_commu.sql:/docker-entrypoint-initdb.d/cmu_commu.sql
